-- KNOWLEDGE_SEARCH Cortex Search service (also included in 02 if schema export captured it).

create or replace cortex search service PM_MEDIATOR.KNOWLEDGE.KNOWLEDGE_SEARCH
	ON CONTENT
	attributes ARTIFACT_ID,SOURCE_SYSTEM_ID,ARTIFACT_TYPE,TITLE,URL,LINE_START,LINE_END
	warehouse='PM_MEDIATOR_WH'
	target_lag='1 hour'
	refresh_mode=INCREMENTAL
	as SELECT ch.CONTENT, ch.CHUNK_ID, ch.ARTIFACT_ID,
         a.SOURCE_SYSTEM_ID, a.ARTIFACT_TYPE, a.TITLE, a.URL,
         ch.LINE_START, ch.LINE_END
  FROM PM_MEDIATOR.KNOWLEDGE.KNOWLEDGE_CHUNK ch
  JOIN PM_MEDIATOR.KNOWLEDGE.KNOWLEDGE_ARTIFACT a ON a.ARTIFACT_ID = ch.ARTIFACT_ID;