-- Least-privilege application role for running Nomy Explores at runtime.
-- Administrative setup (creating objects, loading data, deploying) stays with an admin role;
-- the app itself does NOT need ACCOUNTADMIN. Grant NOMY_APP_ROLE to the app's service user.
-- The skill procedures are EXECUTE AS OWNER, so the app role only needs USAGE on them
-- (AI_COMPLETE / Cortex run under the owner), plus SELECT on data and write access to the
-- DISCOVERY session/artifact tables.

CREATE ROLE IF NOT EXISTS NOMY_APP_ROLE;

GRANT USAGE ON WAREHOUSE PM_MEDIATOR_WH TO ROLE NOMY_APP_ROLE;
GRANT USAGE ON DATABASE PM_MEDIATOR TO ROLE NOMY_APP_ROLE;
GRANT USAGE ON SCHEMA PM_MEDIATOR.MOCK TO ROLE NOMY_APP_ROLE;
GRANT USAGE ON SCHEMA PM_MEDIATOR.KNOWLEDGE TO ROLE NOMY_APP_ROLE;
GRANT USAGE ON SCHEMA PM_MEDIATOR.DISCOVERY TO ROLE NOMY_APP_ROLE;

-- read-only on the operational + knowledge data (and the semantic view)
GRANT SELECT ON ALL TABLES IN SCHEMA PM_MEDIATOR.MOCK TO ROLE NOMY_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PM_MEDIATOR.MOCK TO ROLE NOMY_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PM_MEDIATOR.MOCK TO ROLE NOMY_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PM_MEDIATOR.KNOWLEDGE TO ROLE NOMY_APP_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE PM_MEDIATOR.KNOWLEDGE.KNOWLEDGE_SEARCH TO ROLE NOMY_APP_ROLE;

-- the app persists discovery sessions/turns/artifacts/PRD/tasks
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PM_MEDIATOR.DISCOVERY TO ROLE NOMY_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PM_MEDIATOR.DISCOVERY TO ROLE NOMY_APP_ROLE;

-- the skills (procedures/functions), all EXECUTE AS OWNER
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA PM_MEDIATOR.DISCOVERY TO ROLE NOMY_APP_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA PM_MEDIATOR.DISCOVERY TO ROLE NOMY_APP_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA PM_MEDIATOR.DISCOVERY TO ROLE NOMY_APP_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PM_MEDIATOR.DISCOVERY TO ROLE NOMY_APP_ROLE;

-- example: attach the role + warehouse to the app's service user
-- GRANT ROLE NOMY_APP_ROLE TO USER <app_service_user>;
-- ALTER USER <app_service_user> SET DEFAULT_ROLE = NOMY_APP_ROLE DEFAULT_WAREHOUSE = PM_MEDIATOR_WH;
